### ISSUE TITLE
User credentials store creation failed. User credentials store path is empty

### ISSUE THREAD

**Issue by happilymarrieddad** [hyperledger/firefly-fabconnect#109]
So I've gotten this to work locally but when put in a docker container it fails.

Here is my docker file
```
FROM golang:1.19 AS builder
WORKDIR /app

RUN apt install curl git
RUN git clone https://github.com/hyperledger/firefly-fabconnect
RUN cp -R firefly-fabconnect/* ./
RUN go build -o /app/api main.go

FROM alpine:edge
WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY --from=builder /app/api /app/api
COPY ./fabconnect.yaml /app/fabconnect.yaml
COPY ./ccp.yaml /app/ccp.yaml

CMD ["/app/api","-f","/app/fabconnect.yaml"]
```

Docker-compose file
```
version: '2.1'

networks:
  hyperledger:

services:
  fabconnect:
    container_name: fabconnect
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../crypto-config/:/crypto-config
      - ../state/:/state
      - /tmp/:/tmp
    networks:
      - hyperledger
```

ccp.yaml
```
# ***** certificateAuthorities section *****
# The test-network-nano-bash does not start the Fabric-CA node, but we must keep the 
# certificateAuthorities section because otherwise the fabconnect does not start
certificateAuthorities:
  orderers-ca:
    tlsCACerts:
      path: /state/ca/orderers/server/tls-cert.pem
    url: orderers-ca:7054
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    httpOptions:
      verify: false
  ibm-ca:
    tlsCACerts:
      path: /state/ca/ibm/server/tls-cert.pem
    url: ibm-ca:7054
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    httpOptions:
      verify: false
  oracle-ca:
    tlsCACerts:
      path: /state/ca/oracle/server/tls-cert.pem
    url: oracle-ca:7054
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    httpOptions:
      verify: false

channels:

  mainchannel:

    peers:
      peer0-ibm:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
  
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 1000ms
          maxBackoff: 10s
          backoffFactor: 2.0

client:
  organization: ibm

  logging:
    level: info
  
  cryptoconfig:
    path: /crypto-config
  credentialStore:
    cryptoStore:
      path: /crypto-config/peerOrganizations/ibm/msp
    path: /crypto-config/peerOrganizations/ibm/msp

  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  
  tlsCerts:
    systemCertPool: true

orderers:
  _default:
    grpcOptions:
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
  
  orderer0:
    grpcOptions:
      ssl-target-name-override: orderer0
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem
    url: orderer0:7050
  
  orderer1:
    grpcOptions:
      ssl-target-name-override: orderer1
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem
    url: orderer1:7050
  
  orderer2:
    grpcOptions:
      ssl-target-name-override: orderer2
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem
    url: orderer2:7050

organizations:
  ibm:
    mspid: ibm
    cryptopath: /crypto-config/peerOrganizations/ibm/users/Admin@ibm/msp
    peers:
      - peer0-ibm
      - peer1-ibm
    certificateAuthorities:
      - orderers-ca
      - ibm-ca
      - oracle-ca

peers:

  _default:
    grpcOptions:
      keep-alive-time: 1s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    
  peer0-ibm:
    grpcOptions:
      ssl-target-name-override: peer0-ibm
      grpc.http2.keepalive_time: 15
    url: peer0-ibm:7051
    
    tlsCACerts:
      path: /crypto-config/peerOrganizations/ibm/msp/tlscacerts/ibm-ca-7054.pem

  peer1-ibm:
    grpcOptions:
      ssl-target-name-override: peer1-ibm
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /crypto-config/peerOrganizations/ibm/msp/tlscacerts/ibm-ca-7054.pem
    url: peer1-ibm:7051
    
  peer0-oracle:
    grpcOptions:
      ssl-target-name-override: peer0-oracle
      grpc.http2.keepalive_time: 15
    url: peer0-oracle:7051
    
    tlsCACerts:
      path: /crypto-config/peerOrganizations/oracle/msp/tlscacerts/oracle-ca-7054.pem

  peer1-oracle:
    grpcOptions:
      ssl-target-name-override: peer1-oracle
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /crypto-config/peerOrganizations/oracle/msp/tlscacerts/oracle-ca-7054.pem
    url: peer1-oracle:7051

version: 1.1.0
```

fabconnect.yaml
```
maxinflight: 10
maxtxwaittime: 60
sendconcurrency: 25
receipts:
  maxdocs: 1000
  querylimit: 100
  retryinitialdelay: 5
  retrytimeout: 30
  leveldb:
    path: /app/fabconnect/receipts
events:
  webhooksAllowPrivateIPs: true
  leveldb:
    path: /app/fabconnect/events
http:
  port: 3000
rpc:
  useGatewayClient: true
  configpath: /app/fabconnect/ccp.yaml
```

bash output
```
root@7579eaccfc6d:/app# ls
Dockerfile  ccp.yaml  docker-compose.yaml  events  fabconnect.yaml  fabconnect_linux_x86_64  firefly-fabconnect  receipts
root@7579eaccfc6d:/app# cd firefly-fabconnect/
root@7579eaccfc6d:/app/firefly-fabconnect# ls
CHANGELOG.md  CODE_OF_CONDUCT.md  Dockerfile  MAINTAINERS.md  README.md    cmd	 go.mod  images    main.go  openapi  test
CODEOWNERS    CONTRIBUTING.md	  LICENSE     Makefile	      SECURITY.md  docs  go.sum  internal  mocks    pkg
root@7579eaccfc6d:/app/firefly-fabconnect# go run main.go -f /app/fabconnect.yaml
go: downloading github.com/spf13/viper v1.11.0
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/spf13/cobra v1.4.0
go: downloading github.com/x-cray/logrus-prefixed-formatter v0.5.2
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/julienschmidt/httprouter v1.3.0
go: downloading github.com/rs/cors v1.8.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/Shopify/sarama v1.29.1
go: downloading github.com/xeipuuv/gojsonschema v1.2.0
go: downloading github.com/globalsign/mgo v0.0.0-20181015135952-eeefdecb41b8
go: downloading github.com/oklog/ulid/v2 v2.0.2
go: downloading github.com/syndtr/goleveldb v1.0.1-0.20210305035536-64b5b1c73954
go: downloading github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d
go: downloading github.com/hyperledger/fabric-protos-go v0.0.0-20211118165945-23d738fc3553
go: downloading github.com/hyperledger/fabric-sdk-go v1.0.1-0.20220617091732-e170b98fa821
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/stretchr/testify v1.7.1
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.8.2
go: downloading github.com/spf13/cast v1.4.1
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading golang.org/x/sys v0.0.0-20220422013727-9388b58f7150
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: downloading github.com/golang/protobuf v1.5.2
go: downloading google.golang.org/grpc v1.29.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/klauspost/compress v1.13.5
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading golang.org/x/net v0.0.0-20220412020605-290c469a71a5
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.66.4
go: downloading github.com/magiconair/properties v1.8.6
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/stretchr/objx v0.2.0
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/golang/snappy v0.0.3
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/cloudflare/cfssl v1.4.1
go: downloading google.golang.org/genproto v0.0.0-20220407144326-9054f6ed7bac
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading github.com/hyperledger/fabric-config v0.0.7
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/golang/mock v1.6.0
go: downloading github.com/Knetic/govaluate v3.0.1-0.20171022003610-9aa49832a739+incompatible
go: downloading github.com/google/certificate-transparency-go v1.1.1
go: downloading github.com/zmap/zlint v0.0.0-20190806154020-fd021b4cfbeb
go: downloading github.com/zmap/zcrypto v0.0.0-20190729165852-9051775e6a2e
go: downloading github.com/weppos/publicsuffix-go v0.5.0
Copyright (C) 2021 Kaleido
Licensed under the Apache License, Version 2.0
Version:  (Build Date: )

INFO[0000] Using config file: /app/fabconnect.yaml      
Error: User credentials store creation failed. User credentials store path is empty
Usage:
  fabconnect [flags]

Flags:
  -b, --brokers stringArray                 Comma-separated list of bootstrap brokers
  -i, --clientid string                     Client ID (or generated UUID)
  -f, --configfile string                   Configuration file, must be one of .yml, .yaml, or .json
  -g, --consumer-group string               Client ID (or generated UUID)
  -d, --debug int                           0=error, 1=info, 2=debug (default 1)
  -Z, --debugPort int                       Port for pprof HTTP endpoints (localhost only) (default 6060)
  -E, --events-db string                    Level DB location for subscription management
      --events-polling-int int              Event polling interval (seconds) (default 1)
      --events-priv-ips                     Allow private IPs in Webhooks
      --gateway-client                      Whether to use the client-side gateway support when sending transactions
      --gateway-server                      Whether to use the server-side gateway support when sending transactions (Fabric 2.4 or later only)
  -h, --help                                help for fabconnect
  -H, --leveldb-path string                 Path to LevelDB data directory
  -A, --listen-addr string                  Local address to listen on
  -P, --listen-port int                     Port to listen on (default 8080)
  -m, --maxinflight int                     Maximum messages to hold in-flight
  -D, --mongodb-database string             MongoDB receipt store database
  -C, --mongodb-receipt-collection string   MongoDB receipt store collection
  -U, --mongodb-url string                  MongoDB URL for a receipt store
  -Y, --print-yaml-confg                    Print YAML config snippet and exit
  -x, --receipt-maxdocs int                 Receipt store capped size (new collections only)
  -q, --receipt-query-limit int             Maximum docs to return on a rest call (cap on limit)
  -r, --rpc-config string                   Path to the common connection profile YAML for the target Fabric node
  -p, --sasl-password string                Password for SASL authentication
  -u, --sasl-username string                Username for SASL authentication
  -a, --tls-cacerts string                  CA certificates file (or host CAs will be used) when connecting with the Kafka endpoint
  -c, --tls-clientcerts string              Client certificate file, for mutual TLS auth with the Kafka endpoint
  -k, --tls-clientkey string                Client private key file, for mutual TLS auth with the Kafka endpoint
  -s, --tls-enabled                         Encrypt network connection with TLS (SSL)
      --tls-insecure                        Disable verification of TLS certificate chain
  -n, --topic-in string                     Topic to listen to
  -o, --topic-out string                    Topic to send events to
  -t, --tx-timeout int                      Maximum wait time for an individual transaction (seconds)

User credentials store creation failed. User credentials store path is empty
exit status 1
root@7579eaccfc6d:/app/firefly-fabconnect# %
```
